#!/usr/bin/env bash
set -euo pipefail

# ========================================
# LocalStack Bootstrap Script (No Terraform)
# - Build Lambda ZIPs (same as prod)
# - Create/update Lambdas in LocalStack
# - Create DynamoDB table
# - Create HTTP API routes -> management Lambda
# ========================================

REGION=${REGION:-ap-northeast-1}
ACCOUNT_ID=000000000000
LAMBDA_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/lambda-exec"
LOCALSTACK_ENDPOINT=${LOCALSTACK_ENDPOINT:-http://localhost:4566}
REPO_ROOT=$(cd "$(dirname "$0")/../.." && pwd)

MANAGEMENT_DIR="$REPO_ROOT/lambda/management-device-and-world-data-lambda"
POWER_DIR="$REPO_ROOT/lambda/power-data-registration-lambda"
MANAGEMENT_ZIP="$MANAGEMENT_DIR/lambda_function.zip"
POWER_ZIP="$POWER_DIR/lambda_function.zip"

MANAGEMENT_FN=stg_management_device_and_world_data_lambda
POWER_FN=stg_power_data_registration_lambda
API_NAME=stg_device_and_world_management_api

# awslocal wrapper
awsl() {
  aws --endpoint-url "$LOCALSTACK_ENDPOINT" --region "$REGION" "$@"
}

wait_localstack() {
  echo "[INFO] Waiting for LocalStack to be ready..."
  for i in {1..30}; do
    if awsl sts get-caller-identity >/dev/null 2>&1; then
      echo "[OK] LocalStack is ready"
      return 0
    fi
    sleep 2
  done
  echo "[ERROR] LocalStack not ready after 60s" >&2
  exit 1
}

build_zips() {
  echo "[INFO] Building Lambda ZIPs..."
  (cd "$MANAGEMENT_DIR" && make zip)
  (cd "$POWER_DIR" && make zip)
  echo "[OK] ZIPs built"
}

ensure_dynamodb() {
  local table=tmp_table
  if awsl dynamodb describe-table --table-name "$table" >/dev/null 2>&1; then
    echo "[SKIP] DynamoDB table ${table} exists"
    return
  fi
  awsl dynamodb create-table \
    --table-name "$table" \
    --attribute-definitions \
      AttributeName=session_id,AttributeType=S \
      AttributeName=device_id,AttributeType=S \
    --key-schema \
      AttributeName=session_id,KeyType=HASH \
      AttributeName=device_id,KeyType=RANGE \
    --billing-mode PAY_PER_REQUEST >/dev/null
  echo "[OK] DynamoDB table ${table} created"
}

ensure_lambda() {
  local name=$1 zip=$2
  if ! awsl lambda get-function --function-name "$name" >/dev/null 2>&1; then
    awsl lambda create-function \
      --function-name "$name" \
      --runtime provided.al2023 \
      --handler main \
      --role "$LAMBDA_ROLE_ARN" \
      --timeout 30 \
      --zip-file "fileb://${zip}" >/dev/null
    echo "[OK] Lambda ${name} created"
  else
    awsl lambda update-function-code \
      --function-name "$name" \
      --zip-file "fileb://${zip}" >/dev/null
    echo "[OK] Lambda ${name} code updated"
  fi
  # 環境変数設定 (DB_HOSTはdocker-composeのservice名, sslmode=disableはローカル用)
  awsl lambda update-function-configuration \
    --function-name "$name" \
    --timeout 30 \
    --environment "Variables={DB_HOST=host.docker.internal,DB_PASSWORD=postgres,AWS_REGION=${REGION},AWS_ENDPOINT_URL=http://host.docker.internal:4566}" >/dev/null 2>&1 || true
  echo "[OK] Lambda ${name} env configured"
}

ensure_lambda_function_url() {
  # Lambda Function URL を作成 (HTTP API v2 形式のイベントを送るので Lambda コードと互換性あり)
  local name=$1

  # Function URL が存在するか確認
  local url
  url=$(awsl lambda get-function-url-config --function-name "$name" --query 'FunctionUrl' --output text 2>/dev/null || true)

  if [ -z "$url" ] || [ "$url" = "None" ]; then
    awsl lambda create-function-url-config \
      --function-name "$name" \
      --auth-type NONE \
      --cors AllowOrigins='*',AllowMethods='*',AllowHeaders='*' >/dev/null

    # パブリックアクセス許可
    awsl lambda add-permission \
      --function-name "$name" \
      --action lambda:InvokeFunctionUrl \
      --statement-id FunctionURLAllowPublicAccess \
      --principal '*' \
      --function-url-auth-type NONE >/dev/null 2>&1 || true

    url=$(awsl lambda get-function-url-config --function-name "$name" --query 'FunctionUrl' --output text)
    echo "[OK] Function URL created for ${name}: ${url}"
  else
    echo "[SKIP] Function URL exists for ${name}: ${url}"
  fi
}

configure_nginx_proxy() {
  # Lambda Function URL のホスト名を取得して NGINX config を生成
  local fn_name=$1
  local fn_url
  fn_url=$(awsl lambda get-function-url-config --function-name "$fn_name" --query 'FunctionUrl' --output text 2>/dev/null || echo "")

  if [ -z "$fn_url" ] || [ "$fn_url" = "None" ]; then
    echo "[WARN] Function URL not found for ${fn_name}, skipping NGINX config"
    return
  fi

  # URL からホスト名を抽出 (例: http://xxxxx.lambda-url.ap-northeast-1.localhost.localstack.cloud:4566/)
  local fn_host
  fn_host=$(echo "$fn_url" | sed -E 's|https?://([^/]+)/?|\1|')

  local nginx_conf="$REPO_ROOT/local-environment/nginx/default.conf"

  cat > "$nginx_conf" <<NGINX_EOF
# Auto-generated by bootstrap_localstack.sh
# Lambda Function URL: ${fn_url}
server {
    listen 80;
    server_name _;

    # LocalStack の Lambda Function URL へプロキシ
    location / {
        # LocalStack が返す CORS ヘッダーを除去して重複を防ぐ
        proxy_hide_header Access-Control-Allow-Origin;
        proxy_hide_header Access-Control-Allow-Methods;
        proxy_hide_header Access-Control-Allow-Headers;
        proxy_hide_header Access-Control-Allow-Credentials;

        # CORS 設定 (always を付けないと 4xx/5xx でヘッダーが消える)
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

        # OPTIONS プリフライトリクエストは即座に返す
        # ※ nginx の if ブロックは親の add_header を継承しないため、ここで再定義する
        if (\$request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type, Authorization";
            add_header Access-Control-Max-Age 86400;
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 204;
        }

        resolver 127.0.0.11 valid=10s;
        set \$upstream http://data-collector-localstack:4566;
        proxy_pass \$upstream;
        proxy_set_header Host ${fn_host};
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        # Origin / Referer ヘッダーを除去して LocalStack の CORS チェックを回避
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        proxy_read_timeout 30s;
    }
}
NGINX_EOF

  echo "[OK] NGINX config generated (upstream: ${fn_host})"

  # NGINX をリロード
  docker compose -f "$REPO_ROOT/local-environment/docker-compose.yml" exec -T nginx nginx -s reload 2>/dev/null \
    && echo "[OK] NGINX reloaded" \
    || echo "[WARN] NGINX reload failed (container may not be running)"
}

main() {
  wait_localstack
  build_zips
  ensure_dynamodb
  ensure_lambda "$POWER_FN" "$POWER_ZIP"
  ensure_lambda "$MANAGEMENT_FN" "$MANAGEMENT_ZIP"
  ensure_lambda_function_url "$MANAGEMENT_FN"
  configure_nginx_proxy "$MANAGEMENT_FN"

  local FIXED_URL="http://localhost:8080"

  echo ""
  echo "[DONE] LocalStack bootstrap completed!"
  echo ""
  echo "=========================================="
  echo "Management API (固定URL):"
  echo "  ${FIXED_URL}"
  echo ""
  echo "Example requests:"
  echo "  curl -X POST '${FIXED_URL}/register-new-power-generation-module' \\"
  echo "    -H 'Content-Type: application/json' \\"
  echo "    -d '{\"sessionId\":\"1\",\"deviceId\":\"dev1\",\"deviceType\":\"solar\"}'"
  echo ""
  echo "  curl -X POST '${FIXED_URL}/get-current-world-state' \\"
  echo "    -H 'Content-Type: application/json' \\"
  echo "    -d '{\"sessionId\":\"1\"}'"
  echo ""
  echo "  curl -X POST '${FIXED_URL}/set-equipment-percent' \\"
  echo "    -H 'Content-Type: application/json' \\"
  echo "    -d '{\"sessionId\":\"1\",\"equipment\":\"house\",\"percent\":50}'"
  echo ""
  echo "MQTT:"
  echo "  Publish to localhost:1883 topic 'register/power' -> triggers power Lambda"
  echo "=========================================="
}

main "$@"
